<?php

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <!--\n";
echo "              (^-==-/^)\n";
echo "              >\\ == //<\n";
echo "             :== q''p ==:      _,.---.._\n";
echo "              .__ qp __. ~.-'\"'   |   |''..\n";
echo "                 ^--^  | |    |   , || /  '-. _______ .\":\n";
echo "                  ;| | |    | |     |/   .^-./ _)_)__))_).'\n";
echo "                 /  /      |        /  {/ \n";
echo "             ..-'_           ,.--' _ ) _/\n";
echo "            |  ,_../ - |'---\"\"\"      '-/   |\n";
echo "             --       | |            /_.   |-|\n";
echo "                  __' | |   ._ ___     )  | |__\n";
echo "          _,______'__ddd'_______._____\"\"__ddd'___SK______\n";
echo "                  __________,______.   _._\n";
echo "-->\n";
echo "  <link\n";
echo "    rel=\"stylesheet\"\n";
echo "    type=\"text/css\"\n";
echo "    href=\"https://cdnjs.cloudflare.com/ajax/libs/CSS-Mint/2.0.7/css-mint.min.css\"\n";
echo "  />\n";
echo "  <link rel=\"stylesheet\" type=\"text/css\" href=\"main.css\" />\n";
echo "  <script src=\"https://cdn.riverside.rocks/assets/js/https.js\"></script>\n";
echo "  <div class=\"cm-card\">\n";
echo "    <div class=\"cm-card-header\" style=\"font-size: 30px;\">\n";
echo "      DHHS News\n";
echo "      <a href=\"/account/login.php\"\n";
echo "        ><button\n";
echo "          class=\"cm-btn error line\"\n";
echo "          style=\"float:right;padding:10px;text-decoration:none;\"\n";
echo "        >\n";
echo "          Login\n";
echo "        </button></a\n";
echo "      >\n";
echo "      <a href=\"/about\"\n";
echo "        ><button class=\"cm-btn success\" style=\"float:right;padding:10px;\">\n";
echo "          About Us\n";
echo "        </button></a\n";
echo "      >\n";
echo "      <a href=\"/close\"\n";
echo "        ><button class=\"cm-btn success\" style=\"float:right;padding:10px;\">\n";
echo "          Closings\n";
echo "        </button></a\n";
echo "      >\n";
echo "      <a href=\"/news\"\n";
echo "        ><button class=\"cm-btn success\" style=\"float:right;padding:10px;\">\n";
echo "          News\n";
echo "        </button></a\n";
echo "      >\n";
echo "      <a href=\"/index.html\"\n";
echo "        ><button class=\"cm-btn success\" style=\"float:right;padding:10px;\">\n";
echo "          Home\n";
echo "        </button></a\n";
echo "      >\n";
echo "    </div>\n";
echo "  </div>\n";
echo "  <center>\n";
echo "    <h1>\n";
echo "      Login (Beta)\n";
echo "    </h1>\n";
echo "    <br>\n";
echo "    <div class=\"cm-alert warning\">At this time, the login area is still being developed. We are currently sycing the data from\n";
echo "    our old website. Untill then, please use the <a href=\"https://dhhs.riverside.rocks\">old website</a> to submit posts and\n";
echo "      edit account details.\n";
echo "    </div>\n";
echo "    <br>\n";
echo "    <imput action=\"/accounts/login.php\">\n";
echo "      <label for=\"username\">Username:</label>\n";
echo "      <input type=\"text\" id=\"username\" name=\"password\" disabled /><br /><br />\n";
echo "      <label for=\"password\">Password:</label>\n";
echo "      <input type=\"password\" id=\"password\" name=\"password\" disabled /><br /><br />\n";
echo "      <input type=\"submit\" value=\"Submit\" />\n";
echo "    </imput>\n";
echo "  </center>\n";
echo "</html>\n";

?>
